version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ".:/var/www/app"
  tests:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/var/www/app"
    command:
      - "npm"
      - "test"